// ============================================================
// taskadoollii — build stamp (generated by npm run publish:front)
// Do not edit by hand; overwritten on every publish.
// ============================================================
window.TASKADOLY_BUILD = {
  version: '0.2.0',
  sourceCommit: '397482a',
  frontCommit: '48c7e64',
};
